[project]
name = "organizer-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = 'Aladdin-PC\Aladdin', email = "/" }
]
requires-python = ">=3.8"
dependencies = [
    "aiohttp>=3.10.11",
]

[project.scripts]
organizer-app = "organizer_app:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
